name: to_string
description: Generate toString()
version: 1.0.0
homepage: https://gitlab.com/nkming2/dart-to-string

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.1
  collection: ^1.17.0
  source_gen: ^1.2.6

dev_dependencies:
  build_test: ^2.1.5
  lints: ^2.0.0
  test: ^1.16.0
  code_gen_tester:
    git:
      url: https://github.com/rrousselGit/functional_widget
      ref: v0.10.0
      path: packages/code_gen_tester
