targets:
  $default:
    builders:
      to_string_build:
        options:
          # Map a type by name to a format string. Since the types are mapped by
          # name, this may confuse the generator if you have multiple classes
          # having the same name. In that case you can use
          # formatStringUrlMapping instead
          formatStringNameMapping:
            double: "${$?.toStringAsFixed(1)}"
            List: "[length: ${$?.length}]"
          # Map a type by name to a format string. The types are mapped by their
          # library url (e.g, dart:collection#HashMap)
          formatStringUrlMapping:
            dart:collection#HashMap: "{length: ${$?.length}}"
          # Use the .name property when printing an enum
          useEnumName: true
