name: to_string_build
description: Generate toString()
version: 2.0.0
homepage: https://github.com/nkming2/dart-to-string
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  analyzer: '>=6.0.0'
  build: ">=2.3.1 <2.5.0"
  collection: '>=1.15.0 <2.0.0'
  source_gen: ^2.0.0
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-2.0.0
      path: to_string

dev_dependencies:
  build_test: ">=2.1.5 <3.0.0"
  lints: ">=2.0.0"
  path: any
  test: any

dependency_overrides:
  to_string:
    path: ../to_string
