name: to_string_build
description: Generate toString()
version: 1.1.1
homepage: https://github.com/nkming2/dart-to-string
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: '>=4.0.0'
  build: ^2.3.1
  collection: '>=1.15.0 <2.0.0'
  source_gen: ^1.2.6
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-1.1.0
      path: to_string

dev_dependencies:
  build_test: ^2.1.5
  lints: ^2.0.0
  test: ^1.16.0
  code_gen_tester:
    git:
      url: https://github.com/rrousselGit/functional_widget
      ref: v0.10.0
      path: packages/code_gen_tester
